[manager]
prepend_keymap = [
    { on = [ "<C-i>" ], run = "linemode size_and_mtime", desc = "Show size and modified time" },
    { on = [ "<S-I>" ], run = "linemode none", desc = "Hide linemode metadata" },
]
