[manager]
prepend_keymap = [
    { on = [ "<C-c>" ], run = "quit", desc = "Quit and keep the current directory" },
    { on = [ "<C-i>" ], run = "linemode size_and_mtime", desc = "Show size and modified time" },
    { on = [ "<S-I>" ], run = "linemode none", desc = "Hide linemode metadata" },
]
