[mgr]
linemode = "git_status"

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

[opener]
edit = [
    { run = "$EDITOR %s", block = true, for = "unix" },
]

[open]
prepend_rules = [
    { name = "*.docx", url = "*.docx", use = "edit" },
    { name = "*.doc", url = "*.doc", use = "edit" },
    { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "edit" },
    { mime = "application/msword", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "inode/x-empty", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/toml", use = "edit" },
    { mime = "application/x-yaml", use = "edit" },
    { mime = "application/javascript", use = "edit" },
    { mime = "application/x-shellscript", use = "edit" },
]
