# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"
  theme:
    unstagedChangesColor:
      - "#44FFB1"

git:
  autoFetch: true
