gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
  theme:
    activeBorderColor:
      - "#7cb8ff"
      - bold
    inactiveBorderColor:
      - "#315c78"
    optionsTextColor:
      - "#e8e8e8"
    selectedLineBgColor:
      - "#214969"
    cherryPickedCommitBgColor:
      - "#44FFB1"
    cherryPickedCommitFgColor:
      - "#161a1f"
    defaultFgColor:
      - "#e8e8e8"
    searchMatchBgColor:
      - "#4a86d9"
    searchMatchFgColor:
      - "#0f1317"
    unstagedChangesColor:
      - "#E52E2E"
    stagedChangesColor:
      - "#44FFB1"